#! /bin/sh -e
PIDFILE=/var/run/unsuspendd.pid

_send () {
    if [ -e ${PIDFILE} ]; then
        kill -$1  $(cat ${PIDFILE})
    else
        echo "unsuspendd not run, aborting"
        exit 1
    fi
}

if [ -z "$1" ]; then
    case "$(cat /sys/power/autosuspend)" in 
        0)  echo "Autosuspend off" ;;
        1) echo "Autosuspend off" ;;
    esac
fi


case "$1" in
    prevent)  _send  SIGUSR1  ;;
    okay) _send SIGUSR2 ;;
    status)  cat /sys/power/autosuspend ;;
    *)
        echo "Usage: '$0  (prevent|okay)' to change autosuspend status"
        echo "       '$0  status' to get status in machine readable form"
        exit 1
    ;;
esac
